blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/kaonwong/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Check our development documentation for setup and usage instructions
  - name: 💬 Discussion
    url: https://github.com/kaonwong/skills-expand-your-team-with-copilot/discussions
    about: Join community discussions about the school activities system